#!/usr/bin/env python3
"""Verify that the hierarchical Verilator build is actually hierarchical.

Two independent things are checked, because they can and did disagree:

1. The plan. Parses the authoritative `VM_HIER_LIBS` manifest in the generated
   `V<top>_hier.mk` (one `<dir>/lib<mangledName>.a` entry per specialization
   Verilator actually built), not raw text occurrences of the module name,
   which can appear many times in unrelated prerequisites/commands.
2. The built parent, via `--classes-mk`. A child library can be built,
   archived and linked while the parent still Verilates its own inlined
   `<module>__<params>` specialization of every instance, which is a flat
   build wearing a hierarchical build's artifacts. The plan check alone
   cannot see that.
"""

import argparse
from pathlib import Path
import re


def parse_hier_libs(text):
    match = re.search(r"^VM_HIER_LIBS\s*:=\s*\\\n((?:.*\\\n)*)", text, re.MULTILINE)
    if not match:
        return []
    names = []
    for line in match.group(1).splitlines():
        m = re.search(r"lib([A-Za-z0-9_]+)\.a", line)
        if m:
            names.append(m.group(1))
    return names


def check_parent_is_hierarchical(classes_mk, obj_dir, module, lib_names):
    """Fail if the parent inlined the hier_block instead of using the child."""
    if not classes_mk.is_file():
        raise SystemExit(
            f"parent class list not found: {classes_mk}; the stage-2 top "
            "Verilation (V<top>.mk, regenerated by V<top>_hier.mk with "
            "--hierarchical-block) did not run"
        )

    text = classes_mk.read_text()

    # A parameterized specialization of the hier_block module in the parent's
    # own class list means the parent Verilated the tile itself.
    inlined = sorted(set(re.findall(r"\b\w*" + re.escape(module) + r"__\w+", text)))
    if inlined:
        raise SystemExit(
            f"parent Verilated its own specialization(s) of '{module}' instead "
            f"of linking the prebuilt child librar(y/ies) {', '.join(lib_names)}: "
            + ", ".join(inlined[:5])
            + (" ..." if len(inlined) > 5 else "")
            + f"\nthis is a flat build; check {classes_mk.parent}/../codegen.log "
            "for a HIERBLOCK diagnostic and confirm V<top>.mk was regenerated "
            "by V<top>_hier.mk"
        )

    # And the parent must actually name a built child somewhere.
    haystacks = [text]
    root_header = obj_dir / (classes_mk.name.split("_classes.mk")[0] + "___024root.h")
    if root_header.is_file():
        haystacks.append(root_header.read_text())
    if not any(name in h for name in lib_names for h in haystacks):
        raise SystemExit(
            "parent build never references a built hier_block library ("
            + ", ".join(lib_names)
            + f"); inspected {classes_mk}"
            + (f" and {root_header}" if root_header.is_file() else "")
        )

    print(f"parent check passed: no inlined '{module}' specialization in {classes_mk.name}")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("hier_makefile", type=Path)
    parser.add_argument("--module", default="magia_tile_hier")
    parser.add_argument("--expected-count", type=int, default=1)
    parser.add_argument(
        "--classes-mk",
        type=Path,
        help="generated V<top>_classes.mk; enables the built-parent checks",
    )
    parser.add_argument("--obj-dir", type=Path, help="generated output directory")
    args = parser.parse_args()

    if args.expected_count < 1:
        raise SystemExit("--expected-count must be a positive integer")

    if not args.hier_makefile.is_file():
        raise SystemExit(f"hierarchy makefile not found: {args.hier_makefile}")

    text = args.hier_makefile.read_text()
    lib_names = parse_hier_libs(text)
    if not lib_names:
        raise SystemExit(
            f"no VM_HIER_LIBS entries found in {args.hier_makefile}; "
            "hierarchical Verilation did not build any hier_block library "
            "(the control file's hier_block directive may not have taken effect)"
        )

    module_names = sorted({n for n in lib_names if n.startswith(args.module)})
    if not module_names:
        raise SystemExit(
            f"no specialization of '{args.module}' found; built libraries: "
            + ", ".join(sorted(set(lib_names)))
        )
    if len(module_names) != args.expected_count:
        raise SystemExit(
            f"expected {args.expected_count} specialization(s) of "
            f"'{args.module}', found {len(module_names)}: "
            + ", ".join(module_names)
        )

    other_names = sorted({n for n in lib_names if not n.startswith(args.module)})
    if other_names:
        raise SystemExit(
            "unexpected additional hier_block librar"
            + ("y" if len(other_names) == 1 else "ies")
            + " besides '"
            + args.module
            + "': "
            + ", ".join(other_names)
        )

    if not re.search(r"^hier_build:\s*\$\(VM_HIER_LIBS\)", text, re.MULTILINE):
        raise SystemExit("hier_build does not depend on VM_HIER_LIBS")

    print("hierarchy plan check passed: " + ", ".join(module_names))

    if args.classes_mk is not None:
        obj_dir = args.obj_dir if args.obj_dir is not None else args.classes_mk.parent
        check_parent_is_hierarchical(args.classes_mk, obj_dir, args.module, module_names)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
